name: techbro
favicon: null
layout_spectrum: 0.48517045471817255
typography_spectrum: 0.5896535101346672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6dcc1'
    - '#ebad9e'
    - '#ffffff'
    - '#e37d6f'
    - '#593e6b'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.8060085391625762
purpose: []
